// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LSPServerStatus {
    "name": string;
    "command": string;
    "fileTypes": string[];
    "running": boolean;

    /** Creates a new LSPServerStatus instance. */
    constructor($$source: Partial<LSPServerStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("fileTypes" in $$source)) {
            this["fileTypes"] = [];
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPServerStatus {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileTypes" in $$parsedSource) {
            $$parsedSource["fileTypes"] = $$createField2_0($$parsedSource["fileTypes"]);
        }
        return new LSPServerStatus($$parsedSource as Partial<LSPServerStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
